# Utiliser une image de base existante
FROM python:3.9-slim

# Copier les fichiers du projet dans l'image Docker
COPY . /app

# Se déplacer dans le répertoire de travail
WORKDIR /app

# Installer les dépendances du projet
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    ffmpeg libsm6 libxext6 \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port de l'application
EXPOSE 8080

#healthcheck
HEALTHCHECK CMD curl --fail http://localhost:8080/_stcore/health

# Démarrer l'application
CMD ["python", "clusters.py"]